- name: mysql server setup
  hosts: mysql
  become: yes
  tasks:
  - name: installing PyMySQL and cryptography
    ansible.builtin.pip:
      name: "{{ item }}"
      state: present
    loop:
    - PyMySQL
    - cryptography
  
  - name: installing mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: checking the connection with mysql using root password
    community.mysql.mysql_info:
      login_host: 172.31.94.87
      login_user: root
      login_password: ExpenseApp@1
    register: mysql_info
    ignore_errors: true
  
  - name: mysql mysql_info
    ansible.builtin.debug:
      msg: "{{mysql_info}}"

  - name: creating root passwor for mysql
    ansible.builtin.command: " mysql_secure_installation --set-root-pass ExpenseApp@1 "
    when: mysql_info.failed is true