- name: mysql server setup
  hosts: mysql
  become: yes
  tasks:
  - name: installing mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed
  - name: start mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enable: yes