- name: mysql server setup
  hosts: mysql
  become: yes
  tasks:
  - name: installing mysql
    ansible.builtin.dnf:
      name: mysql
      state: installed
  - name: start mysql
    ansible.builtin.service:
      name: mysql
      state: started
      enable: true