- name: mysql server setup
  hosts: mysql
  become: yes
  tasks:
  - name: installing PyMySQL
    ansible.builtin.pip:
      name: PyMySQL
      state: present

  - name: installing mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name:
    community.mysql.mysql_info:
      login_host: 172.31.23.123
      login_user: root
      login_password: ExpenseApp@1
    register: mysql_info
    ignore_errors: true
  
  - name: mysql mysql_info
    ansible.builtin.debug:
      msg: "{{mysql_info}}"

  - name:
    ansible.builtin.command: " mysql_secure_installation --set-root-pass ExpenseApp@1 "
    when: mysql_info.failed = true