- name: mysql server setup
  hosts: mysql
  become: yes
  tasks:
  - name: installing mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed
  - name: start mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name:
    ansible.builtin.command: mysql -h 172.31.23.123 -u root -p ExpenseApp@1
    register: mysql_fact
  - name:
    ansible.builtin.debug:
      msg: "{{mysql_fact}}"
